version: 0.2
 
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - apt-get install -y unzip

  build:
    commands:
      - echo Build started on `date`
      - zip hello.zip ./index.html 
   
artifacts:
  type: 
  files:
    - index.html
    - appspec.yml
    - SCRIPT/install_dependencies
    - SCRIPT/start_server
